permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Lola"
  description: |
    A website dedicated to the creative works of Lola Sundara.
  font_url: "https://fonts.googleapis.com/css?family=Oswald|Roboto&display=swap"
